services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pulsar:
    image: apachepulsar/pulsar:4.1.1
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - ./pulsar_data:/pulsar/data
